routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/logout',function(){\Auth::logout(); return redirect('/');});

Route::group(['middleware' => ['web']], function(){
/*
	Route::get('auth/login', 'Auth\AuthController@getLogin');
	Route::post('auth/login', 'Auth\AuthController@postLogin');
	Route::get('auth/logout', 'Auth\AuthController@getLogout');

	Route::get('auth/regisgter', 'Auth\AuthController@getRegister');
	Route::post('auth/register', 'Auth\AuthController@postRegister');
*/
	Route::get('blog/{slug}', ['as' => 'blog.single' , 'uses' => 'BlogController@getSingle'])->where('slug', '[\w\d\-\_]+');

	Route::get('blog', ['uses' => 'BlogController@getIndex', 'as' => 'blog.index']);

	Route::get('/contact','PagesController@getContact');

	Route::post('/contact','PagesController@postContact');

	Route::get('/about','PagesController@getAbout');

	Route::get('/', 'PagesController@getIndex');

	Route::resource('posts','PostController');

	Route::resource('categories' , 'CategoryController' , ['except' => 'create']);	

	Route::post('comments/{post_id}', ['uses' => 'CommentsController@store' , 'as' => 'comments.store']);

	Route::get('comments/{id}/edit', ['uses' => 'CommentsController@edit' , 'as' => 'comments.edit']);

	Route::put('comments/{id}', ['uses' => 'CommentsController@update' , 'as' => 'comments.update']);

	Route::delete('comments/{id}', ['uses' => 'CommentsController@destroy' , 'as' => 'comments.destroy']);

	Route::get('comments/{id}/delete', ['uses' => 'CommentsController@delete' , 'as' => 'comments.delete']);

	Route::resource('tags' , 'TagController' , ['except' => 'create']);

});

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    public function posts(){
    	return $this->belongstomany('App\Post');
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Tag;
use Session;

class TagController extends Controller
{

    public function __construct(){
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::all();
        return view('tags.index')->withTags($tags);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request , array('name'=>'required|max:255'));
        $tag = new Tag;
        $tag->name = $request->name;
        $tag->save();
        Session::flash('success','New Tag Was successfully created!');
        return redirect()->route('tags.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $tag = Tag::find($id);
        return view('tags.show')->withTag($tag);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tag = Tag::find($id);
        return view('tags.edit')->withtag($tag);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $tag =Tag::find($id);
        $this->validate($request , ['name' => 'required|max:255']);

        $tag->name = $request->name;
        $tag->save();

        Session::flash('success', 'Successfully saved your tag!');
        return redirect()->route('tags.show',$tag->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tag = Tag::find($id);
        $tag->posts()->detach();

        $tag->delete();

        Session::flash('success','Tag was successfully delete!');

        return redirect()->route('tags.index');
    }
}

resources/views/tags/edit.blade.php
@extends('main')

@section('title', "| Edit Tag")

@section('content')

	{{ Form::model($tag,['route' => ['tags.update',$tag->id] , 'method' => "PUT" ]) }}
		{{ Form::label('name', "Name:") }}
		{{ Form::text('name', null, ['class' => 'form-control']) }}
		<br>
		{{ Form::submit('Save Changes', ['class' => 'btn btn-success']) }}
	{{ Form::close() }}

@endsection

resources/views/tags/index.blade.php
@extends('main')

@section('title', '| All Tags')

@section('content')

	<div class="row">
		<div class="col-md-8">
			<h1>Tags</h1>
			<table class="table">
				<thead>
					<tr>
						<th>#</th>
						<th>Name</th>
					</tr>
				</thead>
				<tbody>
					@foreach($tags as $tag)
					<tr>
						<th>{{ $tag->id }}</th>
						<td><a href="{{ route('tags.show', $tag->id) }}">{{ $tag->name }}</a></td>
					</tr>
					@endforeach
				</tbody>
			</table>
		</div>	
		<div class="col-md-3">
			<div class="well">
				{!! Form::open(['route' => 'tags.store']) !!}
					<h2>New Tag</h2>
					{{ Form::label('name', 'Name:') }}
					{{ Form::text('name' , null, ['class' => 'form-control']) }}
					<br>
					{{ Form::submit('Create New Tag' ,['class' => 'btn btn-primary btn-block']) }}
				{!! Form::close() !!}
			</div>
		</div>
	</div>

@endsection

resources/views/tags/show.blade.php
@extends('main')

@section('title', "| $tag->name Tag")

@section('content')

	<div class="row">
		<div class="col-md-8">
			<br>
			<h1>{{ $tag->name }} Tag <small>{{ $tag->posts()->count() }} Posts </small></h1>
		</div>
		<div class="col-md-1">
			<br><br>
			<a href="{{ route('tags.edit', $tag->id) }}" class="btn btn-sm btn-primary btn-block">編輯</a>
			<br>
		</div>
		<div class="col-md-1">
			<br><br>
			{{ Form::open(['route' => ['tags.destroy',$tag->id ], 'method' => 'DELETE']) }}
				{{ Form::submit('刪除', ['class' => 'btn btn-danger btn-sm btn-block ']) }}
			{{ Form::close() }}
		</div>
	</div>
	<br>
	<div class="row">
		<div class="col-md-12">
			<table class="table">
				<thead>
					<tr>
						<th>#</th>
						<th>標題</th>
						<th>Tags</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					@foreach($tag->posts as $post)
					<tr>
						<th>{{ $post->id }}</th>
						<td>{{ $post->title }}</td>
						<td>
							@foreach($post->tags as $tag)
							<span class="label label-default"> {{ $tag->name }}</span>
							@endforeach
						</td>
						<td><a href="{{ route('posts.show' , $post->id) }}" class="btn btn-default btn-xs btn-primary ">查看</a></td>
					</tr>
					@endforeach
				</tbody>
			</table>
		</div>
	</div>
@endsection