routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/logout',function(){\Auth::logout(); return redirect('/');});

Route::group(['middleware' => ['web']], function(){
/*
	Route::get('auth/login', 'Auth\AuthController@getLogin');
	Route::post('auth/login', 'Auth\AuthController@postLogin');
	Route::get('auth/logout', 'Auth\AuthController@getLogout');

	Route::get('auth/regisgter', 'Auth\AuthController@getRegister');
	Route::post('auth/register', 'Auth\AuthController@postRegister');
*/
	Route::get('blog/{slug}', ['as' => 'blog.single' , 'uses' => 'BlogController@getSingle'])->where('slug', '[\w\d\-\_]+');

	Route::get('blog', ['uses' => 'BlogController@getIndex', 'as' => 'blog.index']);

	Route::get('/contact','PagesController@getContact');

	Route::post('/contact','PagesController@postContact');

	Route::get('/about','PagesController@getAbout');

	Route::get('/', 'PagesController@getIndex');

	Route::resource('posts','PostController');

	Route::resource('categories' , 'CategoryController' , ['except' => 'create']);	

	Route::post('comments/{post_id}', ['uses' => 'CommentsController@store' , 'as' => 'comments.store']);

	Route::get('comments/{id}/edit', ['uses' => 'CommentsController@edit' , 'as' => 'comments.edit']);

	Route::put('comments/{id}', ['uses' => 'CommentsController@update' , 'as' => 'comments.update']);

	Route::delete('comments/{id}', ['uses' => 'CommentsController@destroy' , 'as' => 'comments.destroy']);

	Route::get('comments/{id}/delete', ['uses' => 'CommentsController@delete' , 'as' => 'comments.delete']);

	Route::resource('tags' , 'TagController' , ['except' => 'create']);

});

resources/views/partials/_footer.blade.php
 <hr>

      <p class='text-center'>Copyright hao - All Rights Reserved</p>

resources/views/partials/_head.blade.php
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
	
	<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
	
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    


    <title>Laravel Blog @yield('title')</title> <!-- Change this title for each pages -->
    {{ Html::style('css/select2.min.css') }}
    {{ Html::style('css/style.css') }}
    

@yield('stylesheets')

resources/views/partials/_javascript.blade.php
<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>


   {{ Html::style('js/select2.min.js') }}

resources/views/partials/_messages.blade.php
@if (Session::has('success'))

	<div class="alert alert-success" role="alert">
		<strong>Success:</strong> {{Session::get('success')}}
	</div>

@endif



@if (count($errors) > 0)

	<div class="alert alert-danger" role="alert">
		<strong>Errors:</strong> 
		@foreach ($errors->all() as $error)
			<li>{{ $error }}</li>
		@endforeach
	</div>

@endif

resources/views/partials/_nav.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="{{ Request::is('/') ? "active" : "" }}"><a class="nav-link" href="/">首頁</a></li>
      <li class="{{ Request::is('about') ? "active" : "" }}"><a class="nav-link" href="/about">關於</a></li>
      <li class="{{ Request::is('contact') ? "active" : "" }}"><a class="nav-link" href="/contact">聯絡</a></li>
    </ul>
      <ul class="navbar-nav nav-item dropdown ml-auto">
        @if(Auth::check())
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ Auth::user()->email }}<span class="caret"></span>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{{ route('posts.index') }}">我的貼文</a>
          <a class="dropdown-item" href="{{ route('posts.create') }}">新增貼文</a>
          <a class="dropdown-item" href="{{ route('tags.index') }}">Tags</a>
          <a class="dropdown-item" href="{{ route('categories.index') }}">categroies</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="/logout">登出</a>
        </div>
        @else
        <li><a class="nav-link" href="/login">登入</a></li> 
        @endif
      </ul>
  </div>
</nav>